name: flutter_plus
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  intl: any
  #  shared_preferences: 2.0.1 #本地存储
  dio: 4.0.0 #网络请求
  dio_cookie_manager: ^2.0.0 #网络请求
  retrofit: any #网络请求
  logger: any #网络请求
  permission_handler: ^8.1.2 #权限
  fluro: ^2.0.3 #路由
  connectivity: ^3.0.6  #网络连接
  connectivity_for_web: 0.4.0 #网络连接
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  pull_to_refresh: ^2.0.0 #加载刷新
  freezed_annotation: ^0.14.2 #实体类
  fluttertoast: ^8.0.7 #toast
  flutter_card_swipper: 0.4.0 #轮播图
  multi_image_picker: ^4.8.1 #照片多选
  flutter_form_builder: ^6.0.1
  customizable_space_bar: ^0.2.0
  flutter_html: ^2.1.0
  flustars: ^2.0.1 #工具类
  extended_image: ^4.1.0 #网络图片缓存
  lottie: ^1.1.0 #json格式的动画
  transparent_image: 2.0.0 #透明图像
  json_serializable: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: ^0.14.2
  retrofit_generator: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
